# Generated by Django 5.2.1 on 2025-06-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "street",
                    models.CharField(
                        help_text="Full street address, including house number if applicable.",
                        max_length=255,
                        verbose_name="Street Address",
                    ),
                ),
                (
                    "sub_district",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Kelurahan, Desa.",
                        max_length=100,
                        null=True,
                        verbose_name="Sub-District / Village",
                    ),
                ),
                (
                    "regency",
                    models.CharField(
                        help_text="e.g., Kabupaten Badung, Kota Denpasar.",
                        max_length=100,
                        verbose_name="Regency / City",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
            ],
            options={
                "verbose_name": "Address",
                "verbose_name_plural": "Addresses",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the destination category (e.g., Beach, Mountain, Temple).",
                        max_length=100,
                        unique=True,
                        verbose_name="Category Name",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=25,
                        null=True,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "mail",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Email Address",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact",
                "verbose_name_plural": "Contacts",
            },
        ),
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the facility (e.g., Parking, Toilet, Wi-Fi).",
                        max_length=100,
                        unique=True,
                        verbose_name="Facility Name",
                    ),
                ),
                (
                    "icon_url",
                    models.CharField(
                        blank=True,
                        help_text="URL to an icon image or a CSS class for an icon font.",
                        max_length=255,
                        null=True,
                        verbose_name="Icon URL or Class",
                    ),
                ),
            ],
            options={
                "verbose_name": "Facility",
                "verbose_name_plural": "Facilities",
                "ordering": ["name"],
            },
        ),
    ]
