# Generated by Django 5.2.1 on 2025-06-11 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=120, unique=True, verbose_name="Slug"
            ),
        ),
    ]
