# Generated by Django 5.2.1 on 2025-06-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_alter_category_options_category_created_at_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="facility",
            options={
                "ordering": ["-id"],
                "verbose_name": "Facility",
                "verbose_name_plural": "Facilities",
            },
        ),
        migrations.AddField(
            model_name="facility",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="Created At"
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=120, unique=True, verbose_name="Slug"
            ),
        ),
        migrations.AddField(
            model_name="facility",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="Updated At"
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="icon_url",
            field=models.CharField(
                help_text="URL to an icon image or a CSS class for an icon font.",
                max_length=255,
                verbose_name="Icon URL or Class",
            ),
        ),
    ]
