# Generated by Django 5.2.1 on 2025-06-16 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_alter_facility_options_facility_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facility",
            name="icon_url",
            field=models.TextField(
                help_text="Paste the full <svg>...</svg> code here, or leave blank if using a file-based icon or CSS class.",
                verbose_name="Icon URL or Class",
            ),
        ),
    ]
