# Generated by Django 5.2.1 on 2025-06-17 01:34

import apps.common.models
from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0005_alter_facility_icon_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facility",
            name="icon_url",
        ),
        migrations.AddField(
            model_name="facility",
            name="icon",
            field=models.FileField(
                default=1,
                help_text="Upload an .svg icon file for the facility.",
                upload_to=apps.common.models.facility_icon_path_processor,
                validators=[django.core.validators.FileExtensionValidator(
                    allowed_extensions=['svg'])],
                verbose_name="SVG Icon File",
            ),
            preserve_default=False,
        ),
    ]
