# Generated by Django 5.2.1 on 2025-06-17 03:04

import apps.common.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0008_alter_facility_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facility",
            name="icon",
            field=models.ImageField(
                help_text="Upload an .svg icon file for the facility.",
                upload_to=apps.common.models.facility_icon_path_processor,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["svg"]
                    )
                ],
                verbose_name="SVG Icon File",
            ),
        ),
    ]
