# Generated by Django 5.2.1 on 2025-06-17 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0009_alter_facility_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facility",
            name="name",
            field=models.FileField(
                help_text="Name of the facility (e.g., Parking, Toilet, Wi-Fi).",
                unique=True,
                upload_to="",
                verbose_name="Facility Name",
            ),
        ),
    ]
