# Generated by Django 5.2.1 on 2025-06-17 03:06

import apps.common.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0010_alter_facility_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facility",
            name="icon",
            field=models.FileField(
                help_text="Upload an .svg icon file for the facility.",
                upload_to=apps.common.models.facility_icon_path_processor,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["svg"]
                    )
                ],
                verbose_name="SVG Icon File",
            ),
        ),
        migrations.AlterField(
            model_name="facility",
            name="name",
            field=models.CharField(
                help_text="Name of the facility (e.g., Parking, Toilet, Wi-Fi).",
                max_length=100,
                unique=True,
                verbose_name="Facility Name",
            ),
        ),
    ]
