# Generated by Django 5.2.1 on 2025-06-17 03:07

import apps.common.models
from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0011_alter_facility_icon_alter_facility_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facility",
            name="icon",
            field=models.FileField(
                help_text="Upload an .svg icon file for the facility.",
                upload_to=apps.common.models.facility_icon_path_processor,
                validators=[django.core.validators.FileExtensionValidator(
                    allowed_extensions=['svg'])],
                verbose_name="SVG Icon File",
            ),
        ),
    ]
