# Generated by Django 5.2.1 on 2025-06-17 04:39

import apps.common.models
import apps.common.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0013_alter_facility_icon"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facility",
            name="icon",
            field=models.FileField(
                help_text="Upload an .svg icon file for the facility.",
                upload_to=apps.common.models.facility_icon_path_processor,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["svg"]
                    ),
                    apps.common.validators.validate_file_size,
                    apps.common.validators.validate_svg_file,
                ],
                verbose_name="SVG Icon File",
            ),
        ),
    ]
