# Generated by Django 5.2.1 on 2025-06-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0014_alter_facility_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="district",
            field=models.CharField(
                default=1,
                help_text="e.g., Kecamatan.",
                max_length=100,
                verbose_name="District",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="address",
            name="sub_district",
            field=models.CharField(
                default=1,
                help_text="e.g., Kelurahan, Desa.",
                max_length=100,
                verbose_name="Sub-District / Village",
            ),
            preserve_default=False,
        ),
    ]
