# Generated by Django 5.2.1 on 2025-06-27 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("traveler", "Traveler")],
                default="traveler",
                help_text="Designates the role of the user.",
                max_length=20,
                verbose_name="role",
            ),
        ),
    ]
