# Generated by Django 5.2.1 on 2025-06-28 07:48

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email_verified_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when the user's email was verified.",
                null=True,
                verbose_name="email verified at",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload a profile image for the user.",
                null=True,
                upload_to=apps.users.models.user_image_path,
                verbose_name="profile image",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(
                default=False,
                help_text="Designates whether the user can log into this admin site.",
                verbose_name="staff status",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="User's contact phone number.",
                max_length=20,
                null=True,
                verbose_name="phone number",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("admin", "Admin"), ("traveler", "Traveler")],
                default="traveler",
                help_text="Designates the role of the user within the application.",
                max_length=20,
                verbose_name="role",
            ),
        ),
    ]
