# Generated by Django 5.2.1 on 2025-06-27 02:09

import apps.destinations.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0015_address_district_alter_address_sub_district"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemporaryImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to=apps.destinations.models.temporary_image_path_processor,
                        verbose_name="Temporary Image File",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The official name of the destination.",
                        max_length=255,
                        unique=True,
                        verbose_name="Destination Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        help_text="A URL-friendly version of the name. Leave blank to auto-generate.",
                        max_length=270,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="A detailed description of the destination.",
                        verbose_name="Description",
                    ),
                ),
                (
                    "ticket_price_range",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Rp 50.000 - Rp 100.000, Free, or Starting from Rp 25.000",
                        max_length=100,
                        null=True,
                        verbose_name="Ticket Price Range",
                    ),
                ),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=3,
                        verbose_name="Average Rating",
                    ),
                ),
                (
                    "total_reviews",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Total Reviews"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=False,
                        help_text="Check if the destination is ready to be shown to users.",
                        verbose_name="Is Published",
                    ),
                ),
                (
                    "address",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="common.address",
                        verbose_name="Address",
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="destinations",
                        to="common.category",
                        verbose_name="Categories",
                    ),
                ),
                (
                    "contact",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="common.contact",
                        verbose_name="Contact Information",
                    ),
                ),
                (
                    "facilities",
                    models.ManyToManyField(
                        blank=True,
                        related_name="destinations_with_facility",
                        to="common.facility",
                        verbose_name="Facilities",
                    ),
                ),
            ],
            options={
                "verbose_name": "Destination",
                "verbose_name_plural": "Destinations",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="DestinationImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Upload an image for the destination.",
                        upload_to=apps.destinations.models.destination_image_path_processor,
                        verbose_name="Image File",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="A short description of the image for accessibility and SEO.",
                        max_length=255,
                        null=True,
                        verbose_name="Alt Text",
                    ),
                ),
                (
                    "is_primary",
                    models.BooleanField(
                        default=False,
                        help_text="Set one image as the primary display image for the destination.",
                        verbose_name="Is Primary Image",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Uploaded At"),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="destinations.destination",
                        verbose_name="Destination",
                    ),
                ),
            ],
            options={
                "verbose_name": "Destination Image",
                "verbose_name_plural": "Destination Images",
                "ordering": ["-is_primary", "-uploaded_at"],
            },
        ),
    ]
