# Generated by Django 5.2.1 on 2025-06-29 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destinations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="destination",
            name="is_deleted",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Mark if this destination is moved to trash (soft delete).",
            ),
        ),
    ]
