# Generated by Django 5.2.1 on 2025-06-22 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("destinations", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="destination",
            old_name="category",
            new_name="categories",
        ),
    ]
