# Generated by Django 5.2.1 on 2025-06-17 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("destinations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="destination",
            options={
                "ordering": ["-id"],
                "verbose_name": "Destination",
                "verbose_name_plural": "Destinations",
            },
        ),
        migrations.RemoveField(
            model_name="destination",
            name="operational_hours",
        ),
    ]
