# Generated by Django 5.2.1 on 2025-06-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("destinations", "0002_alter_destination_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="destination",
            name="name",
            field=models.CharField(
                help_text="The official name of the destination.",
                max_length=255,
                unique=True,
                verbose_name="Destination Name",
            ),
        ),
    ]
