# Generated by Django 5.2.1 on 2025-06-22 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="active_context",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
