# Generated by Django 5.2.1 on 2025-06-24 04:32

import apps.chat.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_message_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=apps.chat.storages.ChatImageStorage(),
                upload_to="chat_images/",
            ),
        ),
    ]
