# Generated by Django 5.2.1 on 2025-07-13 03:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("suggestions", "0002_suggestion_suggester"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemporarySuggestionPhoto",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image", models.ImageField(upload_to="suggestions/temp/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
