# Generated by Django 5.2.1 on 2025-07-13 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0015_address_district_alter_address_sub_district"),
        ("suggestions", "0003_temporarysuggestionphoto"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="suggestion",
            name="category",
        ),
        migrations.AddField(
            model_name="suggestion",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="suggestions", to="common.category"
            ),
        ),
        migrations.AlterField(
            model_name="suggestion",
            name="facilities",
            field=models.ManyToManyField(
                blank=True,
                related_name="suggestions_with_facility",
                to="common.facility",
            ),
        ),
        migrations.AlterField(
            model_name="suggestion",
            name="suggester",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="suggestions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Pengusul",
            ),
        ),
    ]
